export const mockEntities = [
  {
    _id: "69256a36812495b2266ce404",
    name: "products",
    displayName: "Products",
    description: "Product catalog management",
    icon: "shopping-cart",
    fields: [
      {
        name: "product_name",
        label: "Product Name",
        type: "text",
        validation: {
          required: true,
          minLength: 3,
          maxLength: 200,
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: true,
        order: 1,
      },
      {
        name: "sku",
        label: "SKU",
        type: "text",
        validation: {
          required: true,
          pattern: "^[A-Z0-9-]+$",
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: true,
        order: 2,
      },
      {
        name: "price",
        label: "Price",
        type: "number",
        validation: {
          required: true,
          min: 0,
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: false,
        order: 3,
      },
      {
        name: "category",
        label: "Category",
        type: "select",
        validation: {
          required: true,
        },
        options: [
          {
            label: "Electronics",
            value: "electronics",
          },
          {
            label: "Clothing",
            value: "clothing",
          },
          {
            label: "Books",
            value: "books",
          },
          {
            label: "Home & Garden",
            value: "home-garden",
          },
        ],
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: false,
        order: 4,
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        validation: {
          maxLength: 1000,
        },
        showInList: false,
        showInForm: true,
        sortable: false,
        searchable: true,
        order: 5,
      },
      {
        name: "is_active",
        label: "Is Active",
        type: "checkbox",
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: false,
        order: 6,
      },
    ],
    timestamps: true,
    softDelete: true,
    enableApi: true,
    apiPath: "/api/v1/products",
    permissions: {
      create: ["admin", "manager"],
      read: ["admin", "manager", "user"],
      update: ["admin", "manager"],
      delete: ["admin"],
    },
    version: 1,
    createdAt: "2025-11-25T08:35:02.327Z",
    updatedAt: "2025-11-25T08:35:02.327Z",
    __v: 0,
  },
  {
    _id: "69256a36812495b2266ce405",
    name: "customers",
    displayName: "Customers",
    description: "Customer relationship management",
    icon: "users",
    fields: [
      {
        name: "full_name",
        label: "Full Name",
        type: "text",
        validation: {
          required: true,
          minLength: 2,
          maxLength: 100,
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: true,
        order: 1,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        validation: {
          required: true,
          pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: true,
        order: 2,
      },
      {
        name: "phone",
        label: "Phone Number",
        type: "text",
        validation: {
          pattern: "^[0-9+\\-\\s()]+$",
        },
        showInList: true,
        showInForm: true,
        sortable: false,
        searchable: true,
        order: 3,
      },
      {
        name: "status",
        label: "Status",
        type: "radio",
        validation: {
          required: true,
        },
        options: [
          {
            label: "Active",
            value: "active",
          },
          {
            label: "Inactive",
            value: "inactive",
          },
          {
            label: "Suspended",
            value: "suspended",
          },
        ],
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: false,
        order: 4,
      },
    ],
    timestamps: true,
    softDelete: true,
    enableApi: true,
    apiPath: "/api/v1/customers",
    permissions: {
      create: ["admin", "sales"],
      read: ["admin", "sales", "support"],
      update: ["admin", "sales"],
      delete: ["admin"],
    },
    version: 2,
    createdAt: "2025-11-24T10:20:15.123Z",
    updatedAt: "2025-11-25T09:15:30.456Z",
    __v: 0,
  },
  {
    _id: "69256a36812495b2266ce406",
    name: "orders",
    displayName: "Orders",
    description: "Order management system",
    icon: "shopping-bag",
    fields: [
      {
        name: "order_number",
        label: "Order Number",
        type: "text",
        validation: {
          required: true,
          pattern: "^ORD-[0-9]{6}$",
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: true,
        order: 1,
      },
      {
        name: "customer",
        label: "Customer",
        type: "reference",
        validation: {
          required: true,
        },
        referenceConfig: {
          entity: "customers",
          displayField: "full_name",
          valueField: "_id",
        },
        showInList: true,
        showInForm: true,
        sortable: false,
        searchable: false,
        order: 2,
      },
      {
        name: "total_amount",
        label: "Total Amount",
        type: "number",
        validation: {
          required: true,
          min: 0,
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: false,
        order: 3,
      },
      {
        name: "order_status",
        label: "Order Status",
        type: "select",
        validation: {
          required: true,
        },
        options: [
          {
            label: "Pending",
            value: "pending",
          },
          {
            label: "Processing",
            value: "processing",
          },
          {
            label: "Shipped",
            value: "shipped",
          },
          {
            label: "Delivered",
            value: "delivered",
          },
          {
            label: "Cancelled",
            value: "cancelled",
          },
        ],
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: false,
        order: 4,
      },
      {
        name: "order_date",
        label: "Order Date",
        type: "datetime",
        validation: {
          required: true,
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: false,
        order: 5,
      },
    ],
    timestamps: true,
    softDelete: false,
    enableApi: true,
    apiPath: "/api/v1/orders",
    permissions: {
      create: ["admin", "sales"],
      read: ["admin", "sales", "warehouse"],
      update: ["admin", "sales", "warehouse"],
      delete: ["admin"],
    },
    version: 1,
    createdAt: "2025-11-23T14:30:45.789Z",
    updatedAt: "2025-11-23T14:30:45.789Z",
    __v: 0,
  },
  {
    _id: "69256a36812495b2266ce407",
    name: "blog_posts",
    displayName: "Blog Posts",
    description: "Content management for blog articles",
    icon: "file-text",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        validation: {
          required: true,
          minLength: 10,
          maxLength: 200,
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: true,
        order: 1,
      },
      {
        name: "slug",
        label: "URL Slug",
        type: "text",
        validation: {
          required: true,
          pattern: "^[a-z0-9-]+$",
        },
        showInList: false,
        showInForm: true,
        sortable: false,
        searchable: false,
        order: 2,
      },
      {
        name: "content",
        label: "Content",
        type: "textarea",
        validation: {
          required: true,
          minLength: 100,
        },
        showInList: false,
        showInForm: true,
        sortable: false,
        searchable: true,
        order: 3,
      },
      {
        name: "author",
        label: "Author",
        type: "reference",
        validation: {
          required: true,
        },
        referenceConfig: {
          entity: "users",
          displayField: "username",
          valueField: "_id",
        },
        showInList: true,
        showInForm: true,
        sortable: false,
        searchable: false,
        order: 4,
      },
      {
        name: "published",
        label: "Published",
        type: "checkbox",
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: false,
        order: 5,
      },
      {
        name: "tags",
        label: "Tags",
        type: "array",
        showInList: true,
        showInForm: true,
        sortable: false,
        searchable: true,
        order: 6,
      },
    ],
    timestamps: true,
    softDelete: true,
    enableApi: true,
    permissions: {
      create: ["admin", "editor"],
      read: ["admin", "editor", "viewer"],
      update: ["admin", "editor"],
      delete: ["admin"],
    },
    version: 3,
    createdAt: "2025-11-20T16:45:20.111Z",
    updatedAt: "2025-11-25T07:22:18.999Z",
    __v: 0,
  },
  {
    _id: "69256a36812495b2266ce408",
    name: "settings",
    displayName: "Settings",
    description: "System configuration settings",
    icon: "settings",
    fields: [
      {
        name: "key",
        label: "Setting Key",
        type: "text",
        validation: {
          required: true,
          pattern: "^[A-Z_]+$",
        },
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: true,
        order: 1,
      },
      {
        name: "value",
        label: "Value",
        type: "text",
        validation: {
          required: true,
        },
        showInList: true,
        showInForm: true,
        sortable: false,
        searchable: true,
        order: 2,
      },
      {
        name: "type",
        label: "Type",
        type: "select",
        validation: {
          required: true,
        },
        options: [
          {
            label: "String",
            value: "string",
          },
          {
            label: "Number",
            value: "number",
          },
          {
            label: "Boolean",
            value: "boolean",
          },
          {
            label: "JSON",
            value: "json",
          },
        ],
        showInList: true,
        showInForm: true,
        sortable: true,
        searchable: false,
        order: 3,
      },
    ],
    timestamps: true,
    softDelete: false,
    enableApi: true,
    apiPath: "/api/v1/settings",
    permissions: {
      create: ["admin"],
      read: ["admin", "developer"],
      update: ["admin"],
      delete: ["admin"],
    },
    version: 1,
    createdAt: "2025-11-22T09:10:00.000Z",
    updatedAt: "2025-11-22T09:10:00.000Z",
    __v: 0,
  },
];
